site: site
title: Bluewind Blog
greetings: No Effort, No Results
description: >-
  Back-End Developer를 꿈꾸며 준비하는 주니어 개발자입니다. Java, Spring을 주로 공부하며 배운것들을 기록하는 블로그입니다. 틀린점이 있다면 댓글 부탁드립니다!
lang: kr-KR
timezone:  Asia/Seoul
repo: https://github.com/Bluewind8791 # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: bluewind # replace with your disqus shortname

author:
  name: name
  bio: bio
  userpicture: 
  username: bluewind # general username
  github: Bluewind8791 # github username
  twitter: # twitter username
  email: bluewind@kakao.com # email adress

# Font Settings
googlewebfonts: family=Play:wght@400;700&family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,300;1,400;1,500;1,600;1,700;1,900&family=Noto+Sans+KR

# URL settings
url: "https://bluewind8791.github.io" # Domain Name of host. [username].github.io for github pages
# url: "http://localhost:4000" # local
baseurl: ""
permalink: pretty

# baseurl: "/Gesko" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wished. always add / in front.


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "/assets/image"
    values:
      image: true

relative_links:
  enabled:     true
  collections: false


